### PR TITLE
Quick fix for 404 link to Code of Conduct

### PR DESCRIPTION
**Pull request by jmitchtx**
Hey there, not much of a contribution, but loving what you've done so far.  I plan to use this gem all/most of the new projects I'm working on.  Who knows, maybe I'll contribute some actual code  next time :D

### CODE REVIEW

**Comment by metaskills** [comment]
Hey James! Thanks for contributing. Super excited to see you are adopting the work here too :)

Hopefully in a few weeks I'll have all the docs in GitHub issues moved over to a new Lamby product site  that will help outline how to get started better. So far the project's Rack integration is solid and I've even run some real world Rails apps thru some tests, no issues.

About the only thing on my wish list past the product site I'm building is making a `bundle exec rake lamby:install` task that creates the basic getting started resources with some Rails generator magic.

* app.rb
* template.yml
* bin/build
* bin/deploy

**Comment by jmitchtx** [comment]
Thanks so much for all you've done here.  I'm super excited to help as much as I can.
One issue I hit yesterday and not sure if I should open a ticket ... but during my first build I was seeing an error ... "RubyBundlerBuilder:CopySource - [Errno 6] No such device or address /path/to/puma.sock".  I put the build in debug mode and then realized puma-dev had dropped the socket file in project/tmp and sam was trying to copy that.  I looked around for a way to tell it to skip binary or socket files or even just to ignore a certain path(tmp/, log/), but alas ... I failed.  So I rm'd the file and sam was happy again.

**Comment by jmitchtx** [comment]
Also, any chance we see some bootstrap'd-by-template capabilities?

$ gem install lamby
$ lamby new my-app --template=react:graphql:aws-record:dynamodb
$ bundle exec rake lamby:install
$ gem install lamby-templates
$ bundle install
$ git add -a -m "All the Lamby goodness!!"
$ rails g model post title:string body:string
   # remembering the previously chosen template .... generates all the
boilerplate for
   #  - reactjs based spa frontend (next, redux, etc) that talks graphql
   #  - graphql (ruby impl via graphql/search_object/etc)
   #  - placeholder tests for both front and back ends
$ say "OMG! This is amazing!!"

I don't know ... just spitballing :D  This is something I may take a look
at later this week, possibly as a separate gem (kiss)



--
James Mitchell
http://www.JamesMitchell.us

**Comment by metaskills** [comment]
>  [Errno 6] No such device or address /path/to/puma.sock"

I've seen that too! I've just been `pkill -USR1 puma-dev` it for a bit as needed.

> I looked around for a way to tell it to skip binary or socket files or even just to ignore a certain path(tmp/, log/), but alas ... I failed.

Thanks, I had not done that yet. Not sure if we should call that out in the docs either? 🤔

> Also, any chance we see some bootstrap'd-by-template capabilities?

I'd like that. Just for starters the `bundle exec rake lamby:install` which installed the app,rb, template, and two bin scripts would suffice.

**Comment by metaskills** [comment]
FYI, got most of the template work done in #35 and the README has a overhauled Getting Started section that leverages this. Cheers!

**Pull request merged**
